aredn: node description, lat/lon display, olsr entries
aredn/aredn_ar71xx pull request #163
Opened 2018-08-28 23:56 UTC by r1de

Added node description to mesh status page
Fixes #161

Added Lat/Lon (if available) to status and mesh pages.
It is displayed above the description and under the node name.
Fixes #145

Added OLSR Routing tables entries to status page just under the memory area
Also added this same info just above the buttons on the mesh status page
Fixes #160

2018-08-29 00:37 UTC, ae6xe commented
propose showing 2 values:  A) total olsr advertised entries; B) # of mesh nodes.   

To get the count of nodes exactly.  It is based on the premise that there are subnet routes listed for the LAN of each node.   Today, there are no other subnet routes advertised, so it's possible in the future this technique could be broken (although maybe still the best technique to estimate the # of nodes).  The command would be:

iproute list table 30 | egrep "/" | wc -l

2018-08-29 00:46 UTC, Orv commented
I got:  
root@WD6EBY-VC-SimiEast-5G:~# iproute list table 30 | egrep "/" | wc -l
-ash: iproute: not found

??

2018-08-29 00:47 UTC, r1de commented
ip route list table 30 | egrep "/" | wc -l

Joe made a typo is all. :)

2018-08-29 00:47 UTC, Orv commented
Better!
root@WD6EBY-VC-SimiEast-5G:~# ip route list table 30 | egrep "/" | wc -l
275

2018-08-29 03:12 UTC, dman776 commented on files/www/cgi-bin/mesh
> +$node_desc = `/sbin/uci get system.\@system[0].description`;
this will throw errors in the unit test.  change from the `cmd` syntax to $(cmd) syntax

2018-08-29 03:14 UTC, dman776 commented on files/www/cgi-bin/mesh
> + `ip route list table 30 | wc -l` .
i would prefer that the commands be performed earlier in the code and saved as a var, then, referenced here in the output.   also, $(cmd) here too

2018-08-29 03:14 UTC, dman776 commented on files/www/cgi-bin/mesh
> + `ip route list table 30 | egrep "/" | wc -l` .
$(cmd)

2018-08-29 03:15 UTC, dman776 commented on files/www/cgi-bin/status
> +    $rcgood=open(FILE, "/etc/latlon");
move this logic before the output starts generating and save to variable.  Reference it here.

2018-08-29 03:15 UTC, r1de commented
Ok, changing... I had it that way and I was trying to be a "one liner" I guess. :)

2018-08-29 03:15 UTC, dman776 commented on files/www/cgi-bin/status
> + `ip route list table 30 | wc -l` .
same as previous comments.

2018-08-29 03:16 UTC, dman776 requested changes
comments inline

2018-08-30 02:53 UTC, dman776 commented on files/www/cgi-bin/mesh
> +($olsrTotal = `ip route list table 30 | wc -l`); #num hosts olsr is keeping track of
no.  these should be like:
$olsrTotal = $("ip route list table 30 | wc -l");

2018-08-30 02:53 UTC, dman776 requested changes
see comments

2018-09-01 01:38 UTC, dman776 approved these changes

2018-09-01 01:39 UTC, merged