aredn: hAP ac lite enable 5GHz LAN Access Point
aredn/aredn_ar71xx pull request #287
Opened 2018-11-28 04:58 UTC by ae6xe

enable ability to bridge LAN physical ports with wireless
LAN Access Point capability. On dual band hAP ac lite,
used in parallel with mesh RF on 2GHz.  Enables future
features on single band devices to turn off mesh RF and
repurposed for mesh LAN Access Point.

closes: #215

2018-11-28 04:59 UTC, ae6xe commented
I've tested this on the following devices:
-hap ac lite
- NS M2 XM
- NS M5 XW
- cpe510v1.1

2018-11-28 05:25 UTC, dman776 requested changes

2018-11-28 05:25 UTC, dman776 commented on files/www/help.html
> +The <strong>Allow others to use my WAN</strong> is an Advance WAN option.
change Advance to Advanced

2018-11-28 05:28 UTC, ae6xe commented on files/www/help.html
> +The <strong>Allow others to use my WAN</strong> is an Advance WAN option.
Corrected.

2018-11-28 05:36 UTC, dman776 approved these changes
tested on my hapaclite and rocket m2

2018-11-28 05:38 UTC, merged

2018-11-29 02:27 UTC, AC0WN commented
Build:  aredn-491-a62fe95-mikrotik-rb-nor-flash-16M-ac-sysupgrade.bin

If your SSID has one or more SPACES in the name the 5 GHz radio does not broadcast when the 5G settings are saved and the router rebooted.  We checked this with a WiFi scanner on several different channels.

As soon as you replace the SPACES in the SSID with UNDERLINES <_> the radio works great.

2018-11-29 02:51 UTC, ae6xe commented
good catch.   Spaces are allowed.  Will submit a change shortly to allow the spaces to correctly save and pass though the config settings.

2018-11-30 06:22 UTC, ae6xe commented
See submitted change:   https://github.com/aredn/aredn_ar71xx/pull/293