enhancement: add additional RF link info to the sysinfo.json file.
aredn/aredn_ar71xx pull request #387
Opened 2019-03-24 00:55 UTC by r1de

Added: current TxMbps value (the negotiated modulation rate)
Added: current signal and noise levels
Added: current set frequency

2019-03-24 03:43 UTC, ae6xe requested changes
The bit rate returned is always for a 20MHz channel.  This value is not compensated for in iwinfo with different channel widths.    Need to divide by 2 if 10MHz and by 4 if 5MHz.    

However..  this value doesn't tell you the rate in use on a given link, it is probably only the highest rate in use somewhere.  If 10 links, there could be 10 different rates in use -- this is the transmit rate not receive.   If the purpose is to show rates on links, then you'd need to pull this from:

/sys/kernel/debug/ieee80211/phy0/netdev\:wlan0/stations/BSS addr of remote node/rc_stats

2019-03-25 04:32 UTC, r1de commented
Ok. Thanks Joe. I did not know that it was showing some "maximum" bit rate (and I didn't even think of the bit rate for each link, duh!).  
How about we just add the Signal, Noise and Frequency and leave the TxMbps for later?  
There is talk of adding the LQ/NLQ info as well to sysinfo.json, that is also going to be a "per link" item, so it makes sense to have the bit rate there as well in the end.

2019-03-25 04:50 UTC, ae6xe commented
A better option would be to pass back the actual throughput of data as show in this table (for each neighbor).   The 'A' row is the actual xmit thoughput (dividing by 2 or 4 for 10 and 5 MHz channels):

/sys/kernel/debug/ieee80211/phy0/netdev:wlan0/stations/MAC address of remote node/rc_stats

All the other measures (SNR, LQ, NLQ) are indirect and 'interesting' and also per neighbor.   If you translated the MAC to an IP address and sent back a table of "to_IP: throughput in mbps", and show on a map link would be the most meaningful.  This value makes different links directly comparable as to their performance.  A 'Quality' link is just one with a value above some throughput threshold.  The only other significant measure is latency of the link.   There's no place to pull this metric from that I know of -- has to be determined with a ping or similar method.

2019-03-25 05:36 UTC, r1de commented
We can wait on all of it then.  
These additions to the sysinfo.json were requested by other users, they want to use them in some other scripts or something, I am not certain.  
Other than to just display this info and maybe use the frequency to check the band without searching through several channel lists, I really had no idea how I would use this on my map.  

But... you just gave me some other ideas, I think.  
I have to fully grok what you just said. :)  
Those rc_stats tables are quite interesting!  
I know I have seen that info before, but you just made it make way more sense! thanks!

2019-03-25 14:03 UTC, dman776 commented
Check the PR that adds iwinfo into the new /api page.   That may be a better place for this info.

Thanks,
Darryl

> On Mar 25, 2019, at 12:36 AM, Eric <notifications@github.com> wrote:
> 
> We can wait on all of it then.
> These additions to the sysinfo.json were requested by other users, they want to use them in some other scripts or something, I am not certain.
> Other than to just display this info and maybe use the frequency to check the band without searching through several channel lists, I really had no idea how I would use this on my map.
> 
> But... you just gave me some other ideas, I think.
> I have to fully grok what you just said. :)
> Those rc_stats tables are quite interesting!
> I know I have seen that info before, but you just made it make way more sense! thanks!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

2019-03-27 05:24 UTC, r1de commented
@ae6xe @dman776 Please test this, it's worked fine on the few nodes I have tried, but still.

2019-03-27 05:32 UTC, r1de commented
Also Dependent on #389

2019-03-27 05:47 UTC, r1de commented
I also moved the some of the sysinfo.json info into functions in the aredn/info.lua file.  
`services` and `hosts`  
This will hopefully help later.  

I can't seem to update that latest commit comment, please update if you can.

2019-03-27 14:51 UTC, r1de commented
I see a couple of things I might have forgotten. Will update in just a bit.

2019-03-27 16:24 UTC, dman776 commented on files/usr/lib/lua/aredn/info.lua
> +function mac2host(dir)
this would make more sense in the aredn.utils library

2019-03-27 16:24 UTC, dman776 commented on files/usr/lib/lua/aredn/info.lua
> +function neighborLinkInfo()
this needs to be in the model scope.
ie.   function model.neighborLinkInfo()

2019-03-27 16:24 UTC, dman776 commented on files/usr/lib/lua/aredn/info.lua
> +function local_services()
this needs to be in the model scope.

2019-03-27 16:25 UTC, dman776 commented on files/usr/lib/lua/aredn/info.lua
> +function all_services()
this needs to be in the model scope.

2019-03-27 16:25 UTC, dman776 commented on files/usr/lib/lua/aredn/info.lua
> +function all_hosts()
this needs to be in the model scope.

2019-03-27 16:25 UTC, dman776 commented on files/usr/lib/lua/aredn/info.lua
> +function link_info()
this needs to be in the model scope.

2019-03-27 16:25 UTC, dman776 commented on files/www/cgi-bin/sysinfo.json
> +	info['services']=all_services()
aredn_info.all_services()

2019-03-27 16:26 UTC, dman776 commented on files/www/cgi-bin/sysinfo.json
> +	info['services_local']=local_services()
aredn_info.local_services()

2019-03-27 16:26 UTC, dman776 commented on files/www/cgi-bin/sysinfo.json
> +	info['services_local']=local_services()
aredn_info.local_services()

2019-03-27 16:26 UTC, dman776 commented on files/www/cgi-bin/sysinfo.json
> +	info['link_info']=link_info()
aredn_info.link_info()

2019-03-27 16:26 UTC, dman776 requested changes
a few inline comments

2019-03-27 17:52 UTC, r1de commented
Ok, I see all those and understand.  
Spent all morning trying to get a good firmware build with the lausocket stuff built in... git is a pain sometimes!  

I will resolve them once I get home.

2019-04-17 02:16 UTC, dman776 commented
Will resubmit with updated PR soon.

2019-04-17 02:16 UTC, closed without merging